import { CurrencyPipe, DatePipe } from '@angular/common';
import { ChangeDetectionStrategy, Component, inject, signal } from '@angular/core';
import { ActivatedRoute, RouterLink } from '@angular/router';
import { switchMap } from 'rxjs';
import { CRM_DATA } from '../../core/data-access/crm-data';
import { Customer } from '../../core/models/customer';
import { StatusBadge } from '../../shared/status-badge';

@Component({
  selector:'app-customer-detail-page', imports:[CurrencyPipe,DatePipe,RouterLink,StatusBadge],
  template:`
    @if(loading()){<div class="card skeleton detail-skeleton"></div>} @else if(!customer()){<section class="state-card"><h1>Cliente no encontrado</h1><a class="button button--primary" routerLink="/customers">Volver a clientes</a></section>} @else if(customer();as c){
      <div class="breadcrumbs"><a routerLink="/customers">Clientes</a><b>›</b><span>{{c.name}}</span></div>
      <header class="customer-hero"><div class="customer-hero__identity"><a class="icon-button" routerLink="/customers" aria-label="Volver">←</a><span class="avatar avatar--lg">{{c.initials}}</span><div><div class="hero-title"><h1>{{c.name}}</h1><app-status-badge [status]="c.status"/></div><p>{{c.id}} · Cliente desde {{c.installationDate|date:'MMMM y':'':'es-MX'}}</p></div></div><div class="page-header__actions"><button class="button">✉ Enviar mensaje</button><button class="button">✎ Editar</button><button class="button button--primary">＋ Registrar pago</button></div></header>
      <section class="detail-stats"><div><span>Mensualidad</span><b>{{c.monthlyFee|currency:'MXN':'symbol-narrow':'1.0-0':'es-MX'}}</b><small>{{c.plan}} · {{c.speed}}</small></div><div><span>Saldo actual</span><b [class.danger-text]="c.currentBalance>0">{{c.currentBalance|currency:'MXN':'symbol-narrow':'1.0-0':'es-MX'}}</b><small>Próximo cobro: día {{c.billingDay}}</small></div><div><span>Estado del servicio</span><b class="success">● En línea</b><small>{{c.ipAddress}} · 18 ms</small></div><div><span>Facturas pagadas</span><b>{{c.payments.length}}</b><small>Historial reciente</small></div></section>
      <nav class="tabs" aria-label="Secciones del cliente">@for(tab of tabs;track tab){<button [class.is-active]="activeTab()===tab" (click)="activeTab.set(tab)">{{tab}}</button>}</nav>
      @switch(activeTab()){
        @case('Resumen'){<section class="detail-grid"><div class="detail-main"><article class="card section-card"><div class="card-heading"><div><h2>Información de contacto</h2><p>Datos principales del cliente</p></div><button class="link-button">Editar</button></div><div class="info-grid"><div><span>Correo electrónico</span><b>{{c.email}}</b></div><div><span>Teléfono</span><b>{{c.phone}}</b></div><div><span>Dirección de instalación</span><b>{{c.address}}, {{c.community}}</b></div><div><span>Ubicación GPS</span><b>{{c.gpsLocation}}</b></div></div></article><article class="card section-card"><div class="card-heading"><div><h2>Servicio contratado</h2><p>Plan y configuración activa</p></div><button class="link-button">Cambiar plan</button></div><div class="service-card"><span class="kpi__icon kpi__icon--blue">⌁</span><div><b>{{c.plan}}</b><small>Internet inalámbrico · {{c.speed}}</small></div><strong>{{c.monthlyFee|currency:'MXN':'symbol-narrow':'1.0-0':'es-MX'}}<small>/ mes</small></strong></div></article><article class="card section-card"><div class="card-heading"><div><h2>Equipos asignados</h2><p>{{c.equipment.length}} dispositivos en el sitio</p></div></div>@for(equipment of c.equipment;track equipment.serial){<div class="equipment-row"><span class="kpi__icon kpi__icon--violet">▣</span><span><b>{{equipment.name}} · {{equipment.model}}</b><small>{{equipment.serial}} · {{equipment.mac}}</small></span><em class="success">● {{equipment.status==='online'?'En línea':equipment.status}}</em></div>}</article></div><aside class="detail-aside"><article class="card section-card"><div class="card-heading"><div><h2>Acciones rápidas</h2></div></div><button>＋ Registrar pago</button><button>▤ Crear factura</button><button>⌁ Cambiar plan</button><button>⌂ Programar visita</button></article><article class="card section-card"><div class="card-heading"><div><h2>Actividad reciente</h2></div></div>@for(item of c.timeline;track item.id){<div class="timeline-item"><i></i><span><b>{{item.title}}</b><small>{{item.detail}}</small><time>{{item.date}}</time></span></div>}</article></aside></section>}
        @case('Facturación'){<article class="card section-card"><div class="card-heading"><div><h2>Facturas recientes</h2><p>Historial de cargos del cliente</p></div><button class="button button--primary">＋ Crear factura</button></div><div class="table-scroll"><table><thead><tr><th>Factura</th><th>Emisión</th><th>Vencimiento</th><th>Total</th><th>Estado</th></tr></thead><tbody>@for(invoice of c.invoices;track invoice.id){<tr><td><b>{{invoice.id}}</b></td><td>{{invoice.issuedAt|date:'dd MMM y':'':'es-MX'}}</td><td>{{invoice.dueAt|date:'dd MMM y':'':'es-MX'}}</td><td>{{invoice.total|currency:'MXN':'symbol-narrow':'1.0-0':'es-MX'}}</td><td><span class="status status--{{invoice.status}}"><i></i>{{invoice.status==='paid'?'Pagada':invoice.status==='overdue'?'Vencida':'Pendiente'}}</span></td></tr>}</tbody></table></div></article>}
        @case('Pagos'){<article class="card section-card"><div class="card-heading"><div><h2>Pagos</h2><p>Movimientos registrados</p></div></div>@for(payment of c.payments;track payment.id){<div class="payment-row"><span class="kpi__icon kpi__icon--green">✓</span><span><b>{{payment.amount|currency:'MXN':'symbol-narrow':'1.0-0':'es-MX'}}</b><small>{{payment.method}} · {{payment.reference}}</small></span><time>{{payment.date|date:'dd MMM y':'':'es-MX'}}</time></div>}</article>}
        @default{<section class="state-card"><span>◇</span><h2>{{activeTab()}}</h2><p>La sección está preparada para conectarse al backend en una fase posterior.</p></section>}
      }
    }`, changeDetection:ChangeDetectionStrategy.OnPush
})
export class CustomerDetailPage{private readonly route=inject(ActivatedRoute);private readonly api=inject(CRM_DATA);readonly customer=signal<Customer|undefined>(undefined);readonly loading=signal(true);readonly activeTab=signal('Resumen');readonly tabs=['Resumen','Facturación','Pagos','Tickets','Notas','Actividad'];constructor(){this.route.paramMap.pipe(switchMap((params)=>this.api.getCustomer(params.get('id')??''))).subscribe((customer)=>{this.customer.set(customer);this.loading.set(false);});}}
